### ISSUE TITLE
Getting Started

### ISSUE THREAD

**Issue by zz85** [mattdesl/three-sdf-text#1]
Hi @mattdesl how would I get started running this project?

I've run `npm install` and `beefy test.js` but get the following error in the browser

```
Cannot read property 'MOUSE' of undefined
```

**Comment by mattdesl** [comment]
I think it likely has to do with ThreeJS version and a conflict with OrbitControls.

I just pushed some things to master that should help. After you git clone master, clear out the `node_modeules` and `bower_components` folders and do the following:

``` sh
npm install
npm run demo
```

Then open `localhost:9966` (might take a couple seconds to bundle everything)

Apologies for the lack of docs/info. This is a pretty WIP/experimental repo. :)

**Comment by zz85** [comment]
no problems, thanks for making this work! :)
