### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by danpaulsmith** [mattdesl/three-sdf-text#2]
Hi Matt, interested to see how this works, how would I use this package? Not really achieving much with npm demo/npm test. Do I need to require it as a module in an app? Thanks

**Comment by danpaulsmith** [comment]
All good, installed wzrd and ran test.js :+1:

**Comment by mattdesl** [comment]
Hey, you may want to check out `three-bmfont-text` module since it is the successor to this. :smile:

Also for this module you can do `npm install && npm run demo` and it should start wzrd for you with the correct flags.

**Comment by danpaulsmith** [comment]
Yea just checked that out :) thanks dude
